#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYNHAHANG")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDMKho(DMKho instance);
    partial void UpdateDMKho(DMKho instance);
    partial void DeleteDMKho(DMKho instance);
    partial void InsertHangHoa(HangHoa instance);
    partial void UpdateHangHoa(HangHoa instance);
    partial void DeleteHangHoa(HangHoa instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhuVuc(KhuVuc instance);
    partial void UpdateKhuVuc(KhuVuc instance);
    partial void DeleteKhuVuc(KhuVuc instance);
    partial void InsertThoiDiem(ThoiDiem instance);
    partial void UpdateThoiDiem(ThoiDiem instance);
    partial void DeleteThoiDiem(ThoiDiem instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DALL.Properties.Settings.Default.QUANLYNHAHANGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DMKho> DMKhos
		{
			get
			{
				return this.GetTable<DMKho>();
			}
		}
		
		public System.Data.Linq.Table<HangHoa> HangHoas
		{
			get
			{
				return this.GetTable<HangHoa>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhuVuc> KhuVucs
		{
			get
			{
				return this.GetTable<KhuVuc>();
			}
		}
		
		public System.Data.Linq.Table<ThoiDiem> ThoiDiems
		{
			get
			{
				return this.GetTable<ThoiDiem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DMKho")]
	public partial class DMKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKho;
		
		private string _TenKho_V;
		
		private System.Nullable<bool> _KhoMacDinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoChanging(string value);
    partial void OnMaKhoChanged();
    partial void OnTenKho_VChanging(string value);
    partial void OnTenKho_VChanged();
    partial void OnKhoMacDinhChanging(System.Nullable<bool> value);
    partial void OnKhoMacDinhChanged();
    #endregion
		
		public DMKho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKho", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKho
		{
			get
			{
				return this._MaKho;
			}
			set
			{
				if ((this._MaKho != value))
				{
					this.OnMaKhoChanging(value);
					this.SendPropertyChanging();
					this._MaKho = value;
					this.SendPropertyChanged("MaKho");
					this.OnMaKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKho_V", DbType="NVarChar(50)")]
		public string TenKho_V
		{
			get
			{
				return this._TenKho_V;
			}
			set
			{
				if ((this._TenKho_V != value))
				{
					this.OnTenKho_VChanging(value);
					this.SendPropertyChanging();
					this._TenKho_V = value;
					this.SendPropertyChanged("TenKho_V");
					this.OnTenKho_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoMacDinh", DbType="Bit")]
		public System.Nullable<bool> KhoMacDinh
		{
			get
			{
				return this._KhoMacDinh;
			}
			set
			{
				if ((this._KhoMacDinh != value))
				{
					this.OnKhoMacDinhChanging(value);
					this.SendPropertyChanging();
					this._KhoMacDinh = value;
					this.SendPropertyChanged("KhoMacDinh");
					this.OnKhoMacDinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangHoa")]
	public partial class HangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHang;
		
		private string _MaHang2;
		
		private string _TenHang_V;
		
		private string _TenHang_E;
		
		private string _DVT;
		
		private System.Nullable<bool> _SuDung;
		
		private System.Nullable<bool> _TinhTonKho;
		
		private string _CachTinhGiaVon;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private System.Nullable<int> _LoaiHH;
		
		private string _NhomHang;
		
		private System.Nullable<int> _STT;
		
		private System.Nullable<bool> _HienThi;
		
		private System.Nullable<double> _GiaBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(string value);
    partial void OnMaHangChanged();
    partial void OnMaHang2Changing(string value);
    partial void OnMaHang2Changed();
    partial void OnTenHang_VChanging(string value);
    partial void OnTenHang_VChanged();
    partial void OnTenHang_EChanging(string value);
    partial void OnTenHang_EChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnSuDungChanging(System.Nullable<bool> value);
    partial void OnSuDungChanged();
    partial void OnTinhTonKhoChanging(System.Nullable<bool> value);
    partial void OnTinhTonKhoChanged();
    partial void OnCachTinhGiaVonChanging(string value);
    partial void OnCachTinhGiaVonChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnLoaiHHChanging(System.Nullable<int> value);
    partial void OnLoaiHHChanged();
    partial void OnNhomHangChanging(string value);
    partial void OnNhomHangChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnHienThiChanging(System.Nullable<bool> value);
    partial void OnHienThiChanged();
    partial void OnGiaBanChanging(System.Nullable<double> value);
    partial void OnGiaBanChanged();
    #endregion
		
		public HangHoa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang2", DbType="Char(10)")]
		public string MaHang2
		{
			get
			{
				return this._MaHang2;
			}
			set
			{
				if ((this._MaHang2 != value))
				{
					this.OnMaHang2Changing(value);
					this.SendPropertyChanging();
					this._MaHang2 = value;
					this.SendPropertyChanged("MaHang2");
					this.OnMaHang2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang_V", DbType="NVarChar(50)")]
		public string TenHang_V
		{
			get
			{
				return this._TenHang_V;
			}
			set
			{
				if ((this._TenHang_V != value))
				{
					this.OnTenHang_VChanging(value);
					this.SendPropertyChanging();
					this._TenHang_V = value;
					this.SendPropertyChanged("TenHang_V");
					this.OnTenHang_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang_E", DbType="NVarChar(50)")]
		public string TenHang_E
		{
			get
			{
				return this._TenHang_E;
			}
			set
			{
				if ((this._TenHang_E != value))
				{
					this.OnTenHang_EChanging(value);
					this.SendPropertyChanging();
					this._TenHang_E = value;
					this.SendPropertyChanged("TenHang_E");
					this.OnTenHang_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuDung", DbType="Bit")]
		public System.Nullable<bool> SuDung
		{
			get
			{
				return this._SuDung;
			}
			set
			{
				if ((this._SuDung != value))
				{
					this.OnSuDungChanging(value);
					this.SendPropertyChanging();
					this._SuDung = value;
					this.SendPropertyChanged("SuDung");
					this.OnSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTonKho", DbType="Bit")]
		public System.Nullable<bool> TinhTonKho
		{
			get
			{
				return this._TinhTonKho;
			}
			set
			{
				if ((this._TinhTonKho != value))
				{
					this.OnTinhTonKhoChanging(value);
					this.SendPropertyChanging();
					this._TinhTonKho = value;
					this.SendPropertyChanged("TinhTonKho");
					this.OnTinhTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CachTinhGiaVon", DbType="NVarChar(20)")]
		public string CachTinhGiaVon
		{
			get
			{
				return this._CachTinhGiaVon;
			}
			set
			{
				if ((this._CachTinhGiaVon != value))
				{
					this.OnCachTinhGiaVonChanging(value);
					this.SendPropertyChanging();
					this._CachTinhGiaVon = value;
					this.SendPropertyChanged("CachTinhGiaVon");
					this.OnCachTinhGiaVonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHH", DbType="Int")]
		public System.Nullable<int> LoaiHH
		{
			get
			{
				return this._LoaiHH;
			}
			set
			{
				if ((this._LoaiHH != value))
				{
					this.OnLoaiHHChanging(value);
					this.SendPropertyChanging();
					this._LoaiHH = value;
					this.SendPropertyChanged("LoaiHH");
					this.OnLoaiHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomHang", DbType="Char(10)")]
		public string NhomHang
		{
			get
			{
				return this._NhomHang;
			}
			set
			{
				if ((this._NhomHang != value))
				{
					this.OnNhomHangChanging(value);
					this.SendPropertyChanging();
					this._NhomHang = value;
					this.SendPropertyChanged("NhomHang");
					this.OnNhomHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienThi", DbType="Bit")]
		public System.Nullable<bool> HienThi
		{
			get
			{
				return this._HienThi;
			}
			set
			{
				if ((this._HienThi != value))
				{
					this.OnHienThiChanging(value);
					this.SendPropertyChanging();
					this._HienThi = value;
					this.SendPropertyChanged("HienThi");
					this.OnHienThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Float")]
		public System.Nullable<double> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH_V;
		
		private System.Nullable<bool> _SuDung;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _MST;
		
		private string _Email;
		
		private string _Fax;
		
		private System.Nullable<int> _LoaiKH;
		
		private string _NhomKH;
		
		private System.Nullable<System.DateTime> _SinhNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKH_VChanging(string value);
    partial void OnTenKH_VChanged();
    partial void OnSuDungChanging(System.Nullable<bool> value);
    partial void OnSuDungChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnMSTChanging(string value);
    partial void OnMSTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnLoaiKHChanging(System.Nullable<int> value);
    partial void OnLoaiKHChanged();
    partial void OnNhomKHChanging(string value);
    partial void OnNhomKHChanged();
    partial void OnSinhNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnSinhNhatChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH_V", DbType="NVarChar(50)")]
		public string TenKH_V
		{
			get
			{
				return this._TenKH_V;
			}
			set
			{
				if ((this._TenKH_V != value))
				{
					this.OnTenKH_VChanging(value);
					this.SendPropertyChanging();
					this._TenKH_V = value;
					this.SendPropertyChanged("TenKH_V");
					this.OnTenKH_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuDung", DbType="Bit")]
		public System.Nullable<bool> SuDung
		{
			get
			{
				return this._SuDung;
			}
			set
			{
				if ((this._SuDung != value))
				{
					this.OnSuDungChanging(value);
					this.SendPropertyChanging();
					this._SuDung = value;
					this.SendPropertyChanged("SuDung");
					this.OnSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MST", DbType="VarChar(30)")]
		public string MST
		{
			get
			{
				return this._MST;
			}
			set
			{
				if ((this._MST != value))
				{
					this.OnMSTChanging(value);
					this.SendPropertyChanging();
					this._MST = value;
					this.SendPropertyChanged("MST");
					this.OnMSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="Int")]
		public System.Nullable<int> LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this.OnLoaiKHChanging(value);
					this.SendPropertyChanging();
					this._LoaiKH = value;
					this.SendPropertyChanged("LoaiKH");
					this.OnLoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhomKH", DbType="Char(10)")]
		public string NhomKH
		{
			get
			{
				return this._NhomKH;
			}
			set
			{
				if ((this._NhomKH != value))
				{
					this.OnNhomKHChanging(value);
					this.SendPropertyChanging();
					this._NhomKH = value;
					this.SendPropertyChanged("NhomKH");
					this.OnNhomKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinhNhat", DbType="Date")]
		public System.Nullable<System.DateTime> SinhNhat
		{
			get
			{
				return this._SinhNhat;
			}
			set
			{
				if ((this._SinhNhat != value))
				{
					this.OnSinhNhatChanging(value);
					this.SendPropertyChanging();
					this._SinhNhat = value;
					this.SendPropertyChanged("SinhNhat");
					this.OnSinhNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuVuc")]
	public partial class KhuVuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKV;
		
		private string _TenKV_V;
		
		private string _TenKV_E;
		
		private string _MayIn;
		
		private System.Nullable<int> _STT;
		
		private System.Nullable<bool> _SuDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKVChanging(string value);
    partial void OnMaKVChanged();
    partial void OnTenKV_VChanging(string value);
    partial void OnTenKV_VChanged();
    partial void OnTenKV_EChanging(string value);
    partial void OnTenKV_EChanged();
    partial void OnMayInChanging(string value);
    partial void OnMayInChanged();
    partial void OnSTTChanging(System.Nullable<int> value);
    partial void OnSTTChanged();
    partial void OnSuDungChanging(System.Nullable<bool> value);
    partial void OnSuDungChanged();
    #endregion
		
		public KhuVuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKV
		{
			get
			{
				return this._MaKV;
			}
			set
			{
				if ((this._MaKV != value))
				{
					this.OnMaKVChanging(value);
					this.SendPropertyChanging();
					this._MaKV = value;
					this.SendPropertyChanged("MaKV");
					this.OnMaKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKV_V", DbType="NVarChar(50)")]
		public string TenKV_V
		{
			get
			{
				return this._TenKV_V;
			}
			set
			{
				if ((this._TenKV_V != value))
				{
					this.OnTenKV_VChanging(value);
					this.SendPropertyChanging();
					this._TenKV_V = value;
					this.SendPropertyChanged("TenKV_V");
					this.OnTenKV_VChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKV_E", DbType="NVarChar(50)")]
		public string TenKV_E
		{
			get
			{
				return this._TenKV_E;
			}
			set
			{
				if ((this._TenKV_E != value))
				{
					this.OnTenKV_EChanging(value);
					this.SendPropertyChanging();
					this._TenKV_E = value;
					this.SendPropertyChanged("TenKV_E");
					this.OnTenKV_EChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MayIn", DbType="NVarChar(100)")]
		public string MayIn
		{
			get
			{
				return this._MayIn;
			}
			set
			{
				if ((this._MayIn != value))
				{
					this.OnMayInChanging(value);
					this.SendPropertyChanging();
					this._MayIn = value;
					this.SendPropertyChanged("MayIn");
					this.OnMayInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int")]
		public System.Nullable<int> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuDung", DbType="Bit")]
		public System.Nullable<bool> SuDung
		{
			get
			{
				return this._SuDung;
			}
			set
			{
				if ((this._SuDung != value))
				{
					this.OnSuDungChanging(value);
					this.SendPropertyChanging();
					this._SuDung = value;
					this.SendPropertyChanged("SuDung");
					this.OnSuDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThoiDiem")]
	public partial class ThoiDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThoiDiem;
		
		private string _TenThoiDiem;
		
		private System.Nullable<System.TimeSpan> _GioBD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThoiDiemChanging(string value);
    partial void OnMaThoiDiemChanged();
    partial void OnTenThoiDiemChanging(string value);
    partial void OnTenThoiDiemChanged();
    partial void OnGioBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OnGioBDChanged();
    #endregion
		
		public ThoiDiem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThoiDiem", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThoiDiem
		{
			get
			{
				return this._MaThoiDiem;
			}
			set
			{
				if ((this._MaThoiDiem != value))
				{
					this.OnMaThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._MaThoiDiem = value;
					this.SendPropertyChanged("MaThoiDiem");
					this.OnMaThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThoiDiem", DbType="NVarChar(50)")]
		public string TenThoiDiem
		{
			get
			{
				return this._TenThoiDiem;
			}
			set
			{
				if ((this._TenThoiDiem != value))
				{
					this.OnTenThoiDiemChanging(value);
					this.SendPropertyChanging();
					this._TenThoiDiem = value;
					this.SendPropertyChanged("TenThoiDiem");
					this.OnTenThoiDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> GioBD
		{
			get
			{
				return this._GioBD;
			}
			set
			{
				if ((this._GioBD != value))
				{
					this.OnGioBDChanging(value);
					this.SendPropertyChanging();
					this._GioBD = value;
					this.SendPropertyChanged("GioBD");
					this.OnGioBDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
